// Data transaksi peminjaman lintas-pengguna, khusus dipakai admin
// (beda dengan app/user/riwayat yang cuma nampilin punya diri sendiri).
// Dipakai di: admin/history (histori peminjaman), admin/pendapatan (rekap
// penghasilan), admin/reports (laporan), dan admin/dashboard (ringkasan).

export const rentalTransactions = [
  {
    id: "NX-2309",
    user: "Rian Pratama",
    item: "Tenda dome 4 orang + Kompor portable",
    category: "Tenda",
    date: "12 Sep 2026",
    month: "2026-09",
    nights: 2,
    total: 140000,
    status: "Aktif",
  },
  {
    id: "NX-2287",
    user: "Siti Aminah",
    item: "Carrier 60L, Sleeping bag -5°C",
    category: "Carrier",
    date: "28 Agu 2026",
    month: "2026-08",
    nights: 2,
    total: 90000,
    status: "Menunggu verifikasi",
  },
  {
    id: "NX-2214",
    user: "Ayu Dian",
    item: "GPS handheld",
    category: "Navigasi",
    date: "15 Jul 2026",
    month: "2026-07",
    nights: 2,
    total: 80000,
    status: "Selesai",
  },
  {
    id: "NX-2199",
    user: "Ayu Dian",
    item: "Tenda dome 2 orang",
    category: "Tenda",
    date: "02 Jul 2026",
    month: "2026-07",
    nights: 3,
    total: 105000,
    status: "Selesai",
  },
  {
    id: "NX-2170",
    user: "Nadia Kusuma",
    item: "Nesting set 4 pcs, Kompor portable + gas",
    category: "Masak",
    date: "22 Jun 2026",
    month: "2026-06",
    nights: 2,
    total: 54000,
    status: "Selesai",
  },
  {
    id: "NX-2151",
    user: "Nadia Kusuma",
    item: "Carrier 80L",
    category: "Carrier",
    date: "10 Jun 2026",
    month: "2026-06",
    nights: 4,
    total: 120000,
    status: "Ditolak",
  },
  {
    id: "NX-2118",
    user: "Rian Pratama",
    item: "Sleeping bag -5°C, Matras gulung",
    category: "Tidur",
    date: "29 Mei 2026",
    month: "2026-05",
    nights: 3,
    total: 84000,
    status: "Selesai",
  },
  {
    id: "NX-2090",
    user: "Siti Aminah",
    item: "Kompas bidik",
    category: "Navigasi",
    date: "14 Mei 2026",
    month: "2026-05",
    nights: 1,
    total: 10000,
    status: "Selesai",
  },
];

export const statusStyle = {
  Aktif: "bg-moss text-fog",
  "Menunggu verifikasi": "bg-amber text-ink",
  Selesai: "bg-line text-ink/60",
  Ditolak: "bg-alert text-fog",
};
