export const categories = ["Semua", "Tenda", "Carrier", "Tidur", "Masak", "Navigasi"];

export const gear = [
  {
    id: "tenda-dome-2p",
    name: "Tenda dome 2 orang",
    category: "Tenda",
    price: 35000,
    unit: "per malam",
    stock: "hijau",
    provider: "Basecamp Merapi",
    note: "Double layer, tahan hujan sedang.",
  },
  {
    id: "tenda-dome-4p",
    name: "Tenda dome 4 orang",
    category: "Tenda",
    price: 55000,
    unit: "per malam",
    stock: "kuning",
    provider: "Basecamp Merapi",
    note: "Sisa 2 unit untuk akhir pekan ini.",
  },
  {
    id: "carrier-60l",
    name: "Carrier 60L",
    category: "Carrier",
    price: 25000,
    unit: "per hari",
    stock: "hijau",
    provider: "Rimba Gear",
    note: "Rain cover termasuk.",
  },
  {
    id: "carrier-80l",
    name: "Carrier 80L",
    category: "Carrier",
    price: 30000,
    unit: "per hari",
    stock: "merah",
    provider: "Rimba Gear",
    note: "Habis, tersedia lagi 14 hari lagi.",
  },
  {
    id: "sleeping-bag",
    name: "Sleeping bag -5°C",
    category: "Tidur",
    price: 20000,
    unit: "per malam",
    stock: "hijau",
    provider: "Basecamp Merapi",
    note: "Cocok untuk jalur dataran tinggi.",
  },
  {
    id: "matras",
    name: "Matras gulung",
    category: "Tidur",
    price: 8000,
    unit: "per malam",
    stock: "hijau",
    provider: "Rimba Gear",
    note: "Ringan, mudah dilipat.",
  },
  {
    id: "kompor-portable",
    name: "Kompor portable + gas",
    category: "Masak",
    price: 15000,
    unit: "per hari",
    stock: "kuning",
    provider: "Dapur Gunung",
    note: "Tabung gas dijual terpisah.",
  },
  {
    id: "nesting",
    name: "Nesting set 4 pcs",
    category: "Masak",
    price: 12000,
    unit: "per hari",
    stock: "hijau",
    provider: "Dapur Gunung",
    note: "Termasuk panci, wajan kecil, dan piring.",
  },
  {
    id: "gps-handheld",
    name: "GPS handheld",
    category: "Navigasi",
    price: 40000,
    unit: "per hari",
    stock: "merah",
    provider: "Rimba Gear",
    note: "Sedang dipinjam, kembali 3 hari lagi.",
  },
  {
    id: "kompas",
    name: "Kompas bidik",
    category: "Navigasi",
    price: 10000,
    unit: "per hari",
    stock: "hijau",
    provider: "Dapur Gunung",
    note: "Sudah dikalibrasi ulang.",
  },
];

export const stockLabel = {
  hijau: "Tersedia",
  kuning: "Terbatas",
  merah: "Habis",
};

export const stockColor = {
  hijau: "bg-moss",
  kuning: "bg-amber",
  merah: "bg-alert",
};
